services:
  # easycode_backend:
  #   network_mode: host
  #   restart: on-failure
  #   build: .
  #   ports:
  #     - 8003:8003
  #   depends_on:
  #     - ec-postgres
  #     # - ec-redis
  #     - ec-mongodb
  ec-postgres:
    network_mode: host
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker-manifest/postgres/postgres-init:/docker-entrypoint-initdb.d
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  # ec-redis:
  #   image: redis:latest
  #   command: --requirepass scut2023
  #   ports:
  #     - 6379:6379
  ec-mongodb:
    network_mode: host
    image: mongo:latest
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ec_backend
    volumes:
      - ./docker-manifest/mongodb/mongo-init:/docker-entrypoint-initdb.d
      - ./data/mongodb-data:/data/db
      - ./data/mongodb-log:/var/log/mongodb
