name: Docker-compose CI

on: [push,pull_request]

jobs:
  docker-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker compose up
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker compose up
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose-database.yml"
      - name: Go test
        run: make test